import filler from './assets/filler.jpg';
import ratemyplate1 from './assets/photos/RateMyPlate_Pic_1.webp'
import ratemyplatevideo from './assets/videos/RateMyPlatePromo.mp4';

// Define and export the projects array
const projects = [
  {
    id: "9",
    title: "Rate My Plate",
    description: "The Rate My Plate application is a comprehensive dining guide for Northeastern University students. Built with a React frontend and Firebase backend, it provides personalized restaurant recommendations based on user preferences, including restaurants that accept Husky Dining Dollars and offer student discounts. Users can browse restaurant details, leave reviews, and engage in real-time chats about their dining experiences. The app also integrates Google Maps for location-based searches, ensuring a seamless experience on both desktop and mobile devices. Rate My Plate combines convenience, community, and exclusive student deals to make dining enjoyable and affordable.",
    short_description: "Dining guide app for Northeastern students.",
    videos: [ratemyplatevideo],
    images: [ratemyplate1, filler, filler],
    technologies: ["React", "JavaScript", "Tailwind CSS", "Firebase", "Leaflet"],
    github: "https://github.com/danctila/rate-my-plate",
    live: "https://ratemyplate.danctil.com",
  },
  {
    id: "8",
    title: "Duck Explorer",
    description: "The Duck Explorer application uses React using TypeScript as a frontend and Express using Javascript as a backend to fetch and analyze random duck images. Images are fetched and analyzed using the random-d API as well as Open AI's gpt-4-vision-preview. The backend sends an image URL on reload to the frontend and on request using the new duck button. When the analyze button is clicked, the current image URL is sent from the frontend to an API POST endpoint on the backend to be sent to the Open AI model with a custom prompt and token limit. The response from the gpt model is then returned back to the frontend for display in a text bubble.",
    short_description: "Duck image fetching and analysis app.",
    videos: [],
    images: [filler, filler, filler],
    technologies: ["Open AI", "React", "TypeScript", "JavaScript", "Express"],
    github: "https://github.com/danctila/duck-explorer",
  },
  {
    id: "7",
    title: "MySchool Program",
    description: "This is a Full Stack React app paired with Express JS and MySQL for the 2023/2024 Connecticut Future Business Leaders of America Coding & Programming competition. The topic for the competition was to create a program that allows your Career and Technical Education Department to collect and store information about business and community partners. The program features a React frontend with Javascript. The backend server was developed using Express JS and includes 5 endpoints for data collection and manipulation from the MySQL database hosted on a Raspberry Pi 4.",
    short_description: "App for partner information management.",
    videos: [],
    images: [filler, filler, filler],
    technologies: ["React", "JavaScript", "Express", "SQL", "Raspberry Pi"],
    github: "https://github.com/danctila/my-school",
  },
  {
    id: "6",
    title: "Total Tech Tools Website",
    description: "This is a freelance web design agency website made in React. This site is fully mobile responsive and includes a variety of modern features including a parallax logo, an animated mobile modal window and a typewriter effect.",
    short_description: "Freelance agency website.",
    videos: [],
    images: [filler, filler, filler],
    technologies: ["React", "TypeScript", "Chakra UI", "Email JS"],
    github: "https://github.com/danctila/total-tech-tools",
    live: "https://totaltechtools.com",
  },
  {
    id: "5",
    title: "Grade Calculator",
    description: "This project is a mobile responsive web app developed for students to use at a high school. It holds a form component in which students can enter grades and a calculated average will return.",
    short_description: "Web app for students to calculate grades.",
    videos: [],
    images: [filler, filler, filler],
    technologies: ["React", "TypeScript", "Chakra UI", "React-Router"],
    github: "https://github.com/danctila/calculator-frontend",
    live: "https://nhsgrader.com",
  },
  {
    id: "4",
    title: "Random Fact Emailer",
    description: "Using a random fact API and Google SMTP email servers, this project sends automated messages to an inputted list of email addresses. The three files are automatically run on a schedule using a Raspberry Pi 4 with Crontab enabled.",
    short_description: "Automated email sender using random facts.",
    videos: [],
    images: [filler, filler, filler],
    technologies: ["Raspberry Pi", "Python", "API", "Google SMTP"],
    github: "https://github.com/danctila/python-email-sender",
  },
  {
    id: "3",
    title: "NYU Website Remake",
    description: "In this project, I focused heavily on design and componentization because the creative vision was not my main task. I wanted to focus on the technical aspects of design more than the creative UI/UX brainstorming.",
    short_description: "Recreation of the NYU website.",
    videos: [],
    images: [filler, filler, filler],
    technologies: ["React", "TypeScript", "CSS", "Chakra UI"],
    github: "https://github.com/danctila/nyu-website",
  },
  {
    id: "2",
    title: "Game Hub",
    description: "This project utilizes an API to fetch data about real games and display them in a simple single-page application. The application is fully mobile responsive and includes searching, categorization, and dark mode features.",
    short_description: "Gaming hub with API integration.",
    videos: [],
    images: [filler, filler, filler],
    technologies: ["React", "API", "TypeScript", "CSS", "Chakra UI"],
    github: "https://github.com/danctila/game-hub",
    live: "https://game-hub-coral-mu.vercel.app/",
  },
  {
    id: "1",
    title: "BlackJack",
    description: "Using only Java, this project recreates a standard 6-deck game of BlackJack. Starting the player off with 2 cards, the player has the option to take a card or not after viewing their current hand as compared to the dealer's current hand.",
    short_description: "Java implementation of 6-deck BlackJack.",
    videos: [],
    images: [filler, filler, filler],
    technologies: ["Java", "BlueJ"],
  },
];

export default projects;
